version: "3.8"

services:
  api:
    image: ${IMAGE:-shu}:${VERSION:-latest}
    platform: "linux/amd64"
    build:
      dockerfile: Dockerfile
      args:
        API_ENVIRONMENT: ${API_ENVIRONMENT:-production}
      context: .
      target: build-app-image
