name: GBPayments Backend - CI

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:


jobs:
  validate-env-variables:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: extractions/setup-just@v1

      - run: |
          just pull-ecs-env-merger
          chmod +x ecs-env-merger
          sudo mv ecs-env-merger /usr/local/bin/ecs-env-merger

      - name: validate "staging" envfiles
        run: |
          echo "{}" > fake_task.json
          ecs-env-merger --mode check_envs --env-file deploy/staging.env --task-definition-file fake_task.json
          
      - name: validate "production" envfiles
        run: |
          echo "{}" > fake_task.json
          ecs-env-merger --mode check_envs --env-file deploy/production.env --task-definition-file fake_task.json
